extends Control

@onready var photo: Photo = $%Photo
@onready var panel: Panel = $%Panel

func _ready() -> void:
	GameState.on_photo_highlighted.connect(_on_photo_highlighted)

func _on_photo_highlighted(texture: Texture) -> void:
	if texture != photo.texture_rect.texture:
		show()
		photo.setup(texture)


func _on_panel_gui_input(event: InputEvent) -> void:
	if event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_LEFT and event.pressed:
		photo.texture_rect.texture = null
		hide()
